# Generated by Django 2.0.7 on 2018-08-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the chore name', max_length=50)),
                ('description', models.TextField(help_text='Enter the description for the chore')),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Chores',
        ),
    ]
