# Generated by Django 2.0.7 on 2018-08-10 00:25

import dashboard.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180809_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='date_end',
            field=models.DateField(default=dashboard.models.Chore.week_from_today),
        ),
        migrations.AlterField(
            model_name='chore',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
