# Generated by Django 2.0.7 on 2018-08-10 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20180809_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='date_start',
        ),
        migrations.AddField(
            model_name='chore',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
