# Generated by Django 2.0.7 on 2018-08-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180809_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='lastupdated',
            field=models.DateField(auto_now=True),
        ),
    ]
