# Generated by Django 2.0.7 on 2018-08-10 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_scheduler_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='lastupdated',
            field=models.DateField(default=datetime.date(2018, 8, 10)),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='start',
            field=models.DateField(default=datetime.date(2018, 8, 10)),
        ),
    ]
