# Generated by Django 2.0.7 on 2018-08-10 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180810_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='lastupdated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
