# Generated by Django 2.0.7 on 2018-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180810_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='lastupdated',
        ),
        migrations.AddField(
            model_name='chore',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
